main_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
  path("", views.Home.as_view(), name="home"),
  path("about/", views.about, name="about"),
  path("travels/", views.travels_index, name="travels_index"),
  path("travels/<int:travel_id>/", views.travels_detail, name="travels_detail"),
  path("travels/create/", views.TravelCreate.as_view(), name="travels_create"),
  path("travels/<int:pk>/update/", views.TravelUpdate.as_view(), name="travels_update"),
  path("travels/<int:pk>/delete/", views.TravelDelete.as_view(), name="travels_delete"),
  path("cats/<int:travel_id>/add_activity/", views.add_activity, name="add_activity"),
  path("accounts/signup", views.signup, name="signup"),
  path("travels/<int:travel_id>/add_photo", views.add_photo, name="add_photo")
]

travelbook/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("", include("main_app.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

main_app/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.db.models.aggregates import Max
from django.urls import reverse

RATING = (
  ("5", "5"),
  ("4", "4"),
  ("3", "3"),
  ("2", "2"),
  ("1", "1")
)
# Create your models here.
class Travel(models.Model):
  city = models.CharField(max_length=100)
  country = models.CharField(max_length=100)
  description = models.TextField(max_length=400)
  date = models.DateField()
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.city

  def get_absolute_url(self):
    return reverse("travels_detail", kwargs={"travel_id": self.pk})
  
class Activity(models.Model):
  activity = models.CharField(max_length=100)
  rating = models.CharField(
    max_length=1,
    choices=RATING,
    default=[0][0]
  )
  travel = models.ForeignKey(Travel, on_delete=models.CASCADE)

  def __str__(self):
    return self.activity

class Photo(models.Model):
  url = models.CharField(max_length=250)
  travel = models.OneToOneField(Travel, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for travel_id: {self.travel_id} @{self.url}"

main_app/forms.py
from django.db import models
from django.forms import ModelForm, fields
from .models import Activity

class ActivityForm(ModelForm):
  class Meta:
    model = Activity
    fields = ["activity", "rating"]

main_app/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.db.models import fields
from django.http import request
from django.shortcuts import redirect, render
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from . models import Travel, Photo
from .forms import ActivityForm
from datetime import date
import uuid
import boto3

S3_BASE_URL = "https://s3.us-east-2.amazonaws.com/"
BUCKET = "travelbookaws"

# Create your views here.

class Home(LoginView):
  template_name = "home.html"

def about(request):
  return render(request, "about.html")

@login_required
def travels_index(request):
  travels = Travel.objects.filter(user=request.user)
  return render(request, "travels/index.html", {"travels" : travels})

@login_required
def travels_detail(request, travel_id):
  travel = Travel.objects.get(id=travel_id)
  activity_form = ActivityForm()
  is_past_tense = travel.date < date.today()
  print("is_past_tense", is_past_tense)
  return render(request, "travels/detail.html", { "travel" : travel, "activity_form" : activity_form, "is_past_tense" : is_past_tense})

class TravelCreate(LoginRequiredMixin ,CreateView):
  model = Travel
  fields = ["city", "country", "description", "date"]

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class TravelUpdate(LoginRequiredMixin ,UpdateView):
  model = Travel
  fields = ["city", "country", "description", "date"]

class TravelDelete(LoginRequiredMixin ,DeleteView):
  model = Travel
  success_url = "/travels/"

@login_required
def add_activity(request, travel_id):
  form = ActivityForm(request.POST)
  if form.is_valid():
    new_activity = form.save(commit=False)
    new_activity.travel_id = travel_id
    new_activity.save()
  return redirect("travels_detail", travel_id=travel_id)

@login_required
def add_photo(request, travel_id):
  photo_file = request.FILES.get("photo-file", None)
  if photo_file:
    s3 = boto3.client("s3")
    key = uuid.uuid4().hex + photo_file.name[photo_file.name.rfind("."):]
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      photo = Photo(url=url, travel_id=travel_id)
      travel_photo = Photo.objects.filter(travel_id=travel_id)
      if travel_photo.first():
        travel_photo.first().delete()
      photo.save()
    except Exception as err:
      print('An error occurred uploading file to S3: %s' % err)
  return redirect('travels_detail', travel_id=travel_id)

def signup(request):
  error_message = ""
  if request.method == "POST":
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect("travels_index")
    else:
      error_message = "Invalid signup!! Please try again."
  form = UserCreationForm()
  context = {"form" : form, "error_message" : error_message}
  return render(request, "signup.html", context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About Travel Book</h1>
<hr />
<p class="about-text">
  This is your go to app for all your travel & excurision blogging. Feel free to add all your past and future travel destinations. For me and many others traveling is when we are at our happiest and also make the best memories that end up lasting forever. I have created a app that will allow a user to signup and login to keep a log of all their vacations, sometimes you may have done an activity/excursion that you loved or you hated, you can keep all those details in one place with Travel Book.
</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'images/travelbook-icon.png' %}"
>
<link
    rel="stylesheet" 
    type="text/css" 
    href="{% static 'css/base.css' %}"
>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
  <title>Travel Book</title>
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="header-logo-container">
      <a href="{% url 'home' %}">
        <img
        class="logo-img"
        style="width: 200px; height: 150px"
        src="{% static 'images/travelbook-logo.png' %}" 
        alt="The Travel Book Logo"
        >
      </a>
    </div>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'travels_index' %}">All Travels</a></li>
        <li><a href="{% url "travels_create" %}">Add a Travel</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url "home" %}">Login</a></li>
        <li><a href="{% url "signup" %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block head %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>

<link 
href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
crossorigin="anonymous"/>

<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>

<script 
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
  crossorigin="anonymous"
></script>

{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h1>Welcome to Travel Book</h1>
{% endif %}

<section class="logo-container">
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="travel-container carousel-item active">
      <img src=" {% static 'images/travel-new-york.svg' %}" class="d-block w-100" alt="New York">
    </div>
    <div class="travel-container carousel-item">
      <img src="{% static 'images/travel-italy.svg' %}" class="d-block w-100" alt="Italy">
    </div>
    <div class="travel-container carousel-item">
      <img src="{% static 'images/travel-japan.svg' %}" class="d-block w-100" alt="Japan">
    </div>
    <div class="travel-container carousel-item">
      <img src="{% static 'images/travel-palestine.svg' %}" class="d-block w-100" alt="Palestine">
    </div>
    <div class="travel-container carousel-item">
      <img src="{% static 'images/travel-copenhagen.svg' %}" class="d-block w-100" alt="Copenhagen">
    </div>
  </div>
</div>
</section>

{% if not user.is_authenticated %}
<section>
  <form action="{% url 'home' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}">
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>
{% endif %}

{% endblock %}

main_app/templates/main_app/travel_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/travel-delete.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Delete {{ travel.city }}, {{ travel.country }}?</h1>
  <img src="{% static 'images/add-travel.svg' %}" alt="Add Travel"/>
</div>
<h2>Are your sure you want to delete this travel? Last chance.</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a href="{% url "travels_detail" travel.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/travel_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link 
  rel="stylesheet" 
  href="{% static 'css/mcdp.css' %}"
>
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<script defer src={% static 'js/travel-form.js' %}></script>
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/form.css' %}"
/>
{% endblock %}

{% block content %}

<div class="page-header">
  {% if object %}
  <h1>Edit a Travel</h1>
  {% else %}
  <h1>Add a Travel</h1>
  {% endif %}
  <img src="{% static 'images/add-travel.svg' %}" alt="Add Travel"/>
</div>
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/add-travel.svg' %}" alt="Passport Signup"/>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/travels/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/travel-detail.css' %}"
/>
<script defer src="{% static 'js/travel-detail.js' %}"></script>
{% endblock %}

{% block content %}

<section class="travel-container">
  <div class="travel-img">
    {% if travel.photo.url %}
    <img 
      src="{{travel.photo.url}}" 
      alt="A photo of travel to {{travel.city}}"
      class="usr-img"
    >
    {% else %}
    <img 
    src="{% static 'images/travelbook.svg' %}" 
    alt="The Travel Book"
    >
    {% endif %}
  </div>
  <div class="travel-details">
    <h1>{{ travel.city }}, {{ travel.country }}</h1>
    {% if is_past_tense %}
    <h2>Traveled on {{ travel.date }}.</h2>
    {% else %}
    <h2>Traveling on {{ travel.date }}.</h2>
    {% endif %}
    <p>{{ travel.description }}</p>
    <div class="travel-actions">
      <a href="{% url 'travels_update' travel.id %}" class="btn warn">Edit</a>
      <a href="{% url 'travels_delete' travel.id %}" class="btn danger">Delete</a>
    </div>
    <h3>Change the {{ travel.city }}, {{travel.country}} photo</h3>
    <p id="file-name"></p>
    <form 
      action="{% url 'add_photo' travel.id %}"
      enctype="multipart/form-data"
      method="POST"
    >
      {% csrf_token %}
      <label class="btn secondary">
        Choose photo
        <input type="file" name="photo-file" id="file-input">
      </label>
      <button type="submit" class="btn submit">Upload Photo</button>
    </form>
  </div>
</section>
<div class="activities-container">
  <section class="activities">
    <div class="subsection-title">
      <h2>Excursions/Activities</h2>
      <img 
        src="{% static 'images/activity.svg' %}" 
        alt="Surfer"
      />
    </div>
    <h3>Add a Excursion/Activity</h3>
    <form
      action={% url 'add_activity' travel.id %}
      method="POST"
      class="subsection-content"
    >
      {% csrf_token %}
      {{ activity_form.as_p }}
      <button 
        type="submit" 
        class="btn submit"
      >
        Add Excursion/Activity
      </button>
    </form>
    <h3>All Excursions/Activities</h3>
    {% if travel.activity_set.all.count %}
      <table>
        <thead>
          <tr><th>Activity</th><th>Rating</th></tr>
        </thead>
        <tbody>
          {% for activity in travel.activity_set.all %}
            <tr>
              <td>{{activity.activity}}</td>
              <td>{{activity.rating}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p class="subsection-content">Nothing added yet</p>
    {% endif %}
  </section>
</div>
{% endblock %}

main_app/templates/travels/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/travel-index.css' %}"/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>{{ user.username }}'s - Travel Log</h1>
  <img src="{% static 'images/globe.svg' %}" alt="" />
</section>

<section class="card-container">
  {% for travel in travels %}
    <div class="card">
      <a href="{% url 'travels_detail' travel.id %}">
        <div class="card-content">
          <div class="card-img-container">
            {% if travel.photo.url %}
            <img 
              src="{{travel.photo.url}}" 
              alt="A photo of travel to {{travel.city}}"
              class="usr-img"
            >
            {% else %}
            <img 
            src="{% static 'images/travelbook.svg' %}" 
            alt="The Travel Book"
            >
            {% endif %}
          </div>
          <h2 class="card-title">{{ travel.city }}, {{ travel.country }}</h2>
          <p>{{ travel.date }}</p>
          <p><small>{{ travel.description }}</small></p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>
{% endblock %}